spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://192.168.10.146:5432/psyassistant}
    username: ${DB_USERNAME:psyassistant}
    password: ${DB_PASSWORD:psyassistant}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
